### ISSUE TITLE
Bad state: No element

### ISSUE THREAD

**Issue by AbdrahmanKafo96** [flutterbuddy1/geocoder2#17]
I've been using it for a long time, but now it's not working and i got this message 
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: No element
E/flutter (14161): #0      List.first (dart:core-patch/growable_array.dart:343:5)
E/flutter (14161): #1      Geocoder2.getDataFromCoordinates (package:geocoder2/src/geocoder2.dart:25:44)
E/flutter (14161): <asynchronous suspension>
E/flutter (14161): #2      MyApp.printdata (package:untitled/main.dart:12:20)
E/flutter (14161): <asynchronous suspension>

**Comment by ZacharyHandshoe** [comment]
I have the same problem. I had it working on Flutter Web, but it does not function with the Android restricted key

**Comment by AbdrahmanKafo96** [comment]
It turns out that the subscription is not activated, so you need to renew the subscription
