### ISSUE TITLE
Bad state: No element  Did not find frame.

### ISSUE THREAD

**Issue by zakihou** [flutterbuddy1/geocoder2#20]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: No element
E/FrameEvents(15179): updateAcquireFence: Did not find frame.
E/flutter (15179): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: No element
E/flutter (15179): #0      List.first (dart:core-patch/growable_array.dart:343:5)
E/flutter (15179): #1      Geocoder2.getDataFromCoordinates (package:geocoder2/src/geocoder2.dart:25:44)

**Comment by priy-smart** [comment]
i get same
